import "@styles/globals.css";
import Header from "@components/Header";
import {GoogleAnalytics} from "@next/third-parties/google";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      
      <body>
        <Header />
        {children}
        <GoogleAnalytics gaId="G-W8KWKKPK86" />
      </body>
    </html>
  );
}
